spring:
  application:
    name: product-service

server:
  port: 8082

# Configuraci√≥n de Eureka Client para Docker
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: product-service

logging:
  level:
    com.example.productservice: DEBUG
    com.netflix.eureka: INFO
